spring.application.name=wellrun-backend

spring.datasource.url=jdbc:mysql://localhost:3306/health_db?serverTimezone=Asia/Seoul
spring.datasource.username=root

spring.datasource.password=0000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

vworld.api.key=7BCD08F9-8BE3-3C07-83CE-A66E9C385F46